#!/usr/bin/env node

let fs = require("fs")
let Phrase = require("dawidl022-palindrome")

let text = fs.readFileSync("phrases.txt", "utf-8");
let lines = text.trim().split("\n");

lines.forEach(line => {
  if (new Phrase(line).palindrome()) {
    console.log("Palindrome detected:", line);
  }
});
