#!/usr/bin/env node

const urllib = require("urllib");
const Phrase = require("dawidl022-palindrome");
let url = 'https://cdn.learnenough.com/phrases.txt'

urllib.request(url, { followRedirect: true }, function (error, data, response) {
  let body =  data.toString();
  const lines = body.split("\n");
  const palindromes = lines.filter(line => new Phrase(line).palindrome());

  palindromes.forEach(palindrome => {
    console.log("palindrome detected:", palindrome)
  })

});
